<?php
namespace Magentron\MetaphoneSpanish\Tests;

use PHPUnit\Framework\TestCase;

class BaseTestCase extends TestCase
{
    /** @codeCoverageIgnore  */
    public function words()
    {
        return array(
            array('X',                    'X'     ),
            array('Xochimilco',           'XXMLK' ),
            array('a',                    'A'     ),
            array('abedul',               'AVDL'  ),
            array('abollar',              'AVYR'  ),
            array('aboyar',               'AVYR'  ),
            array('acción',               'AXN'   ),
            array('alhamar',              'ALAMR' ),
            array('aquino',               'AKN'   ),
            array('arrebato',             'ARRVT' ),
            array('axioma',               'AXM'   ),
            array('cara',                 'KR'    ),
            array('caricia',              'KRZ'   ),
            array('cerilla',              'ZRY'   ),
            array('cesar',                'ZSR'   ),
            array('chato',                'XT'    ),
            array('chocolate',            'XKLT'  ),
            array('cid',                  'ZD'    ),
            array('cien',                 'ZN'    ),
            array('clon',                 'KLN'   ),
            array('clown',                'KLUN'  ),
            array('col',                  'KL'    ),
            array('complicado',           'KMPLKD'),
            array('conciencia',           'KNZNZ' ),
            array('cuco',                 'KK'    ),
            array('down',                 'DUN'   ),
            array('ecologia',             'EKLJ'  ),
            array('encima',               'ENZM'  ),
            array('enzima',               'ENZM'  ),
            array('escalera',             'ESKLR' ),
            array('españa',               'ESPNY' ),
            array('expansión',            'EXPNSN'),
            array('garrulo',              'GRRL'  ),
            array('gato',                 'GT'    ),
            array('gengibre',             'JNJVR' ),
            array('gente',                'JNT'   ),
            array('gitano',               'JTN'   ),
            array('google',               'GGL'   ),
            array('gragea',               'GRJ'   ),
            array('grajea',               'GRJ'   ),
            array('guerra',               'GRR'   ),
            array('hola',                 'OL'    ),
            array('huevo',                'UV'    ),
            array('jamón',                'JMN'   ),
            array('ke',                   'K'     ),
            array('llaves',               'YVS'   ),
            array('macho',                'MX'    ),
            array('membrillo',            'MMVRY' ),
            array('mi',                   'M'     ),
            array('ochooomiiiillllllll',  'OXMYY' ),
            array('paella',               'PY'    ),
            array('paquete',              'PKT'   ),
            array('pero',                 'PR'    ),
            array('perro',                'PRR'   ),
            array('pingüino',             'PNUN'  ),
            array('que',                  'K'     ),
            array('queso',                'KS'    ),
            array('reacción',             'RXN'   ),
            array('rebosar',              'RVSR'  ),
            array('rebozar',              'RVZR'  ),
            array('risa',                 'RS'    ),
            array('scalera',              'ESKLR' ),
            array('si',                   'S'     ),
            array('su',                   'S'     ),
            array('te',                   'T'     ),
            array('tu',                   'T'     ),
            array('wHISKY',               'UISKY' ),
            array('waterpolo',            'UTRPL' ),
            array('web',                  'UV'    ),
            array('webo',                 'UV'    ),
            array('xilófono',             'XLFN'  ),
            array('xochitl',              'XXTL'  ),
            array('xocolate',             'XKLT'  ),
            array('xplosion',             'EXPLSN'),
            array('yema',                 'YM'    ),
            array('zapato',               'ZPT'   ),
            array('ácaro',                'AKR'   ),
            array('ácido',                'AZD'   ),
        );
    }
}
